baseURL = "/"
languageCode = "en-us"
title = "Bob Coffee"
theme = "kube"
description = "Kube is a professional  and a responsive Hugo theme for developers and designers that offers a documentation section mixed with a landing page and a blog"
Paginate = 20
[Params]
  RSSLink = "/index.xml"
  author = "Bobski Ross design" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myemail@myaddress.xxx"


[[menu.main]]
    name = "Journal"
    weight = -20
    url = "/journal/"
[[menu.main]]
    name = "Contact"
    weight = 0
    url = "/contact/"
