baseURL = "/"
languageCode = "en-us"
title = "Bob Coffee"
theme = "kube"
description = "Kube is a professional  and a responsive Hugo theme for developers and designers that offers a documentation section mixed with a landing page and a blog"
Paginate = 10
[Params]
  RSSLink = "/index.xml"
  author = "Bob Coffee" # add your company name
  github = "" # add your github profile name
  linkedin = "bob-coffee" # add your linkedin profile
  fivehundredpx = "bobcoffee" # add your 500px profile
  insta = "bobski_ross" # add your 500px profile
  email = "bob@bobcoffee.io"


[[menu.main]]
    name = "Journal"
    weight = 1
    url = "/journal/"
[[menu.main]]
    name = "About Me"
    weight = 2
    url = "/about/"
